### PR TITLE
Add routine HCOIO_IsValid

### PR DESCRIPTION
**Pull request by christophkeller**
### Name and Institution (Required)

Name: Christoph Keller
Institution: NASA GMAO / Morgan State University

### Confirm you have reviewed the following documentation

- [x ] [Contributing guidelines](https://hemco.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### Describe the update

`HCOIO_IsValid` is a wrapper routine to check if a HEMCO container has a valid field attached to it. In an ESMF environment, there are edge cases where the fields can change from defined to undefined over the course of a simulation. This routine returns the validity of a field as determined by ESMF routine `ESMFL_field_is_undefined`. In a non-ESMF environment, this routine simply returns whether the queried field name has a corresponding data container or not. 

### Expected changes

Zero diff

### Reference(s)

N/A

### Related Github Issue(s)

N/A

### CODE REVIEW

**Review by viral211 — APPROVED** [review]
Looks fine to me.

**Comment by lizziel** [comment]
What ESMF version are you using? I cannot find `ESMFL_field_is_undefined` in the latest version, or in 8.4 which we use in GCHP.

**Comment by christophkeller** [comment]
Oh! This was tested using MAPL v2.34.3. Adding `ESMFL_field_is_undefined` was inspired by a similar procedure used in [GAAS_GridComp](https://github.com/GEOS-ESM/GEOSchem_GridComp/blob/develop/GAAS_GridComp/GAAS_GridCompMod.F90#L498C33-L498C33). This is still working in the latest version of GEOS, so I had hoped that this does not cause any issues. But I have to admit that I don't fully understand the differences between ESMF/MAPL as used by GCHP vs. GEOS.

**Comment by lizziel** [comment]
Ah, okay. I will hold off on bringing it into the standard model until we update to MAPL3. We are using MAPL 2.26.0 until then.

**Comment by lizziel** [comment]
I should add that if there are significant delays to MAPL 3 perhaps we should update MAPL sooner.

**Pull request merged**
