### PR TITLE
HEMCO 3.2.2

### PR DESCRIPTION
**Pull request by lizziel**
This PR upgrades HEMCO version from 3.0.0 to 3.2.2. This upgrade is a requirement for use with GEOS-Chem 13.3.4 which is a separate PR for GEOS-Chem. See https://github.com/GEOS-ESM/geos-chem/pull/1.

### CODE REVIEW

**Comment by lizziel** [comment]
@christophkeller, this HEMCO branch is now ready for testing, along with the GEOS-Chem branch in PR https://github.com/GEOS-ESM/geos-chem/pull/1. I built and ran these branches successfully in `GEOSgcm` main branch as of Jan 3 ([68e53fae](https://github.com/GEOS-ESM/GEOSgcm/commit/68e53fae5187857f8e952f9d897e6d6ddabd124c)). See my `/nb/GEOS_CF/develop+13.3/` directory on discover for source code and run directory.

I am looking at the merge conflict and see there is a divergence between `GEOS/develop` and the branch I grabbed for running GEOS-Chem (`feature/cakelle2/GCCv13.0.0_GEOS`). The `CMakeLists.txt` update causing the conflict is from 2020, for GOCART. Let me know if I should change the target branch of this. For example, if you want to merge this into one of your branches rather than the main branch.

**Comment by christophkeller** [comment]
Can you change the target branch to `geos/develop` [https://github.com/GEOS-ESM/HEMCO/tree/geos/develop](https://github.com/GEOS-ESM/HEMCO/tree/geos/develop), rather than `GEOS/develop`. We should also remove `GEOS/develop`, since this branch is stale and its name is indeed extremely confusing...

**Comment by lizziel** [comment]
All set. I didn't see there was also a `geos/develop`! Confusing indeed.

**Comment by lizziel** [comment]
I think the check checked failed because I added the label after creating the PR. Is there a way to resubmit the check now that there is a label?

**Pull request merged**
